sudo: false

language: node_js

node_js:
  - "7"
  - "6"
  - "5"
  - "4"

before_script:
  - npm install

script:
  - npm run lint
  - istanbul cover ./node_modules/tape/bin/tape --report lcovonly -- ./test/*.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
